# Run this with
# sudo ./bin/filebeat -e -c filebeat.yml -d "publish"

filebeat.inputs:

- type: log
  paths:
    - /root/dataset/secure/*
  tags: ["secure"]

output.logstash:
  hosts: ["http://localhost:5044"]
